upgrade
    input strings into config
submodules and dependencies


setup
    compiled code
    compiled code dir
genpath outside of matlab
genpath 
    only 2 times
          don't follow symlinks
          use find,rg, faster?
           # rg --no-ignore --hidden --files -g "!{.fonts,.cache,.local,.julia/**,.java/**,matlab}"'
           find -L . -type d -not -path '*/\.git*' -not -path '*/\.svn*' -not -path '*/\_old*/' 
    bin -> like genconf
        then no gen
        but then new files don't get added automatically...
        wrk - working directory
rehash classes etc function
base tools
    px system tools
    px matlab tools
    px git tools
    CfgRd
    logging tools
    DepTools

check non-std dependencies
"environmental variables"

config file naming 
    host.prj.lib.config
log naming
    host.prj.lib.subr.log


optional dependencies section in config
    prompt to download
broken symlinks can act as non-existant files -> problem with history

stable only in root config
    dire stable -> lib
 one-liner
 no stable-projects directory
 only workspace
 everything into lib
 symlinked to workspace

(p) prj
(s) src  <- tools
(l) lib 
(e) etc
(t) tlb  
(m) media <- default save directory
(v) var <- logging
    dat
(?) tmp 


   - imap
   - dir

   - config directory for projects
   - rm px and number command from history  
  (rm history)

- default root should be ../
- get home directory in windows
  
- recursive dependencies

- make lib files read only
  chmod -w
- link toolboxes if marked as such in config
- +modules?
- do gtags within workspaces?
* logging
timestamps
capturing output...
    probably matlab bulitins
run script from shell command
* C code
readlink
ln
* Dep handler
- indep px dep handler
  for people who don't want to use px, but want to use packages
** px setup script
download px from github packages
** px packaging
create setup script, which specifies which px packaged version
* media handler
default save location
* var handler
crashdumps
* History  NOTES
%com.mathworks.mlservices.MLCommandHistoryServices.getAllHistory
%com.mathworks.mlservices.MLCommandHistoryServices.getSessionHistory
%com.mathworks.mlservices.MLCommandHistoryServices.add(string)
% removeall
% save
% getSessionHistory
%com.mathworks.ide.cmdline.CommandHistory.deleteAllHistoryForDesktop;
%com.mathworks.mlservices.MLCommandHistoryServices.
%com.mathworks.mlservices.MLExecuteServices.consoleEval

history option


com.mathworks.mde.cmdhist.CmdHistory.getInstance
com.mathworks.mde.cmdhist.AltHistory.getInstance()
com.mathworks.mde.cmdhist.AltHistory.getRecalledCommands

import java.io.File


file = new File(com.mathworks.util.FileUtils.getPreferencesDirectory , "History.xml");

<command batch="true" repeat="2 error="true" "execution_time="" ></command>
<command time_stamp"">>%-- 05/13/2020 03:42:37 PM --%</command>

# run commmand, add to history
com.mathworks.mlservices.MLExecuteServices.executeCommand('')
# run command, do not add to history
com.mathworks.mlservices.MLExecuteServices.consoleEval('')

# add to history
com.mathworks.mlservices.MLCommandHistoryServices.add('px')
?exec time
?repeat
?error
?batch

