submodules and dependencies?

base tools
    CfgRd
    RW
split out git into own thing? -> matGit

"environmental variables" -> px config file

config file naming 
    host.prj.lib.config
log naming
    host.prj.lib.subr.log

by project options
   data

optional dependencies section in config
    prompt to download
history problem
      broken symlinks can act as non-existant files -> problem with 

more options
      bTmp
      bVar
      bMedia
      bData


if updating removing, make sure that dependencies are removed too

(p) prj
(s) src  <- tools
(l) lib 
(e) etc
(t) tlb  (remove?)
(m) media <- default save directory
(v) var <- logging
    dat
(?) tmp 

- default root should be ../
- get home directory in windows
  
- recursive dependencies

- link toolboxes if marked as such in config
- +modules?
- do gtags within workspaces?
* logging
timestamps
capturing output...
    probably matlab bulitins
run script from shell command
* Dep handler
- indep px dep handler
  for people who don't want to use px, but want to use packages
** px setup script
download px from github packages
** px packaging
create setup script, which specifies which px packaged version
* media handler
default save location
* var handler
crashdumps
* History  NOTES
%com.mathworks.mlservices.MLCommandHistoryServices.getAllHistory
%com.mathworks.mlservices.MLCommandHistoryServices.getSessionHistory
%com.mathworks.mlservices.MLCommandHistoryServices.add(string)
% removeall
% save
% getSessionHistory
%com.mathworks.ide.cmdline.CommandHistory.deleteAllHistoryForDesktop;
%com.mathworks.mlservices.MLCommandHistoryServices.
%com.mathworks.mlservices.MLExecuteServices.consoleEval

history option


com.mathworks.mde.cmdhist.CmdHistory.getInstance
com.mathworks.mde.cmdhist.AltHistory.getInstance()
com.mathworks.mde.cmdhist.AltHistory.getRecalledCommands

import java.io.File


file = new File(com.mathworks.util.FileUtils.getPreferencesDirectory , "History.xml");

<command batch="true" repeat="2 error="true" "execution_time="" ></command>
<command time_stamp"">>%-- 05/13/2020 03:42:37 PM --%</command>

# run commmand, add to history
com.mathworks.mlservices.MLExecuteServices.executeCommand('')
# run command, do not add to history
com.mathworks.mlservices.MLExecuteServices.consoleEval('')

# add to history
com.mathworks.mlservices.MLCommandHistoryServices.add('px')
?exec time
?repeat
?error
?batch

